QualiSystems/cloudshell-orch-sandbox

sandbox_scripts/environment/setup/setup_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/7)

Fixed wait for ip & auto event usage. There was an import missing.

---

sandbox_scripts/environment/setup/setup_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/9)

added call to prepare connectivity

---

sandbox_scripts/environment/setup/setup_script.py

Added call to PrepareSandboxConnectivity in setup as the first thing we do during the setup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/10)

Added call to PrepareSandboxConnectivity in setup as the first thing 

---

sandbox_scripts/environment/teardown/teardown_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/11)

Added call to cleanupsandboxconnectivity at the end

---

sandbox_scripts/environment/teardown/teardown_script.py
sandbox_scripts/helpers/vm_details_helper.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/14)

Updated teardown to remove VMs using new flow

---

sandbox_scripts/environment/setup/setup_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/16)

fixing deleted code for prepare connectivity

---

sandbox_scripts/environment/setup/setup_script.py
sandbox_scripts/helpers/resource_helpers.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/20)

added helper to get_resource_from_cache_or_server

---

sandbox_scripts/environment/setup/setup_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/22)

changed connectivity so that **ALL** CVCs will be connected

---

sandbox_scripts/environment/setup/setup_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/29)

setp scriot to call configure apps instead of install apps

---

sandbox_scripts/environment/setup/setup_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/30)

setup script bug fix

---

sandbox_scripts/environment/setup/setup_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/31)

Cloudshell orch sandbox 157823

---

sandbox_scripts/environment/setup/setup_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/33)

Bug 159212 fix

---

sandbox_scripts/environment/setup/setup_script.py
sandbox_scripts/environment/teardown/teardown_script.py

Rename 'reservation' to 'sandbox' in console output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/35)

Setup & teardown scripts

---

sandbox_scripts/environment/teardown/teardown_script.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/37)

remove redundant API calls during teardown_script

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/44)

support sandbox stages

---

QualiConf.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/45)

add QualiConf.ini

---

cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/47)

re-raise the original exception to stop the setup if there is a discovery error

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py
cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/50)

move preapare_connectivity to sandbox class

---

cloudshell-orch-core/cloudshell/workflow/orchestration/components.py
cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py
cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_orchestrator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/52)

Bug161339/custom setup script doesn't return full address 1

---

cloudshell-orch-core/cloudshell/workflow/profiler/env_profiler.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/59)

disable profiler when reservatioContext doesn't exists

---

SandboxOrchestrationPackage/DataModel/datamodel.xml
SandboxOrchestration_specs/sandbox_setup.ini
SandboxOrchestration_specs/sandbox_teardown.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/60)

update the orchestration scripts to be version 2.0 (resolve bug 161776)

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py
cloudshell-orch-core/cloudshell/workflow/orchestration/workflow.py

adding another stage to to the workflow - preparation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/66)

Feature add prepare - adding preparation step to workflow

---

cloudshell-orch-core/cloudshell/workflow/orchestration/workflow.py

adding docstrings to workflow functions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/70)

adding docstrings that explains about the components to workflow

---

cloudshell-orch-core/cloudshell/workflow/orchestration/apps_configuration.py
cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/72)

Made api.ConfigureApps to print the output

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/73)

include PrepareSandboxConnectivity in Preparation stage

---

cloudshell-orch-core/cloudshell/workflow/orchestration/apps_configuration.py
cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py
pack_local.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/78)

Fix regression bugs (163876, 163880) caused by 163120

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py

Fix Bug 164054 - error msg in activity feed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/82)

Fix Bug 164054 - error msg in activity feed

---

SandboxOrchestration/environment_scripts/env_setup/requirements.txt
SandboxOrchestration/environment_scripts/env_teardown/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/86)

increment version to 1.6

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/88)

handle error msg using logger exception.

---

cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py
cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_orchestrator.py
cloudshell-orch-core/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/89)

orchestration to support refresh vm details after connect / power on

---

cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/90)

safer checking if need to refresh vm details

---

cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py

renamed successfullyAutoloadedAppsNames to successfully_autoloaded_apps_names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/94)

Noam 164714 remap cvc

---

cloudshell-orch-core/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/95)

change 9.0 to 8.3

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py
cloudshell-orch-core/cloudshell/workflow/orchestration/workflow.py

adding a new type of exception, using it in the validation of the workflow and throwing the inner exception to the setup, when required by the "supress_exception" flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/96)

adding exception info and options for excetion in setup

---

cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py
cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_orchestrator.py
cloudshell-orch-core/cloudshell/workflow/orchestration/teardown/default_teardown_logic.py
cloudshell-orch-core/cloudshell/workflow/orchestration/teardown/default_teardown_orchestrator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/102)

Change auto events behaviour

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py
pack_local.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/104)

add some logging and messages

---

SandboxOrchestration/environment_scripts/env_restore/__main__.py
cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/105)

restore logic

---

cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/107)

Auto Events

---

cloudshell-orch-core/cloudshell/workflow/helpers/sandbox_helpers.py
cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/108)

change context to contain user name of the user executed a command

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/110)

error message without alot of error wrapping

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/111)

fixed critical bug that prevented save sandbox

---

cloudshell-orch-core/cloudshell/workflow/orchestration/teardown/default_teardown_logic.py

This reverts commit 4e0212827819a7709951e2b425b49321c6663292.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/113)

Revert "fixing auto power off & auto delete in teardown"

---

cloudshell-orch-core/cloudshell/workflow/orchestration/components.py
cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py
cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_orchestrator.py
cloudshell-orch-core/cloudshell/workflow/orchestration/teardown/default_teardown_orchestrator.py

This reverts commit e22f87a24ad518ea7759f06938dddfca17002891.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/115)

Revert "Fix bug 168107"

---

cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/120)

support 2nd gen attributes

---

Quali-Shells-Open-Source.rtf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/129)

add license

---

cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py
cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_orchestrator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/130)

activate routes in setup

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/131)

user param fix - 8.3 patch 3

---

SandboxOrchestration/environment_scripts/env_restore/requirements.txt
SandboxOrchestration/environment_scripts/env_save/requirements.txt
SandboxOrchestration/environment_scripts/env_setup/requirements.txt
SandboxOrchestration/environment_scripts/env_teardown/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/133)

cloudshell-orch-core>=3.0.0.0,<3.1.0.0

---

SandboxOrchestration/environment_scripts/env_save/requirements.txt
SandboxOrchestration/environment_scripts/env_setup/requirements.txt
SandboxOrchestration/environment_scripts/env_teardown/requirements.txt
cloudshell-orch-core/cloudshell/workflow/helpers/resource_helpers.py
cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py
cloudshell-orch-core/cloudshell/workflow/orchestration/teardown/default_teardown_logic.py
cloudshell-orch-core/requirements.txt
cloudshell-orch-core/tests/test_sandbox.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/134)

Intreduce cloudshell logger

---

cloudshell-orch-core/cloudshell/workflow/orchestration/sandbox.py
cloudshell-orch-core/cloudshell/workflow/orchestration/setup/default_setup_logic.py
cloudshell-orch-core/cloudshell/workflow/orchestration/teardown/default_teardown_logic.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qualisystems/cloudshell-orch-sandbox/135)

replaces exception.message (which was removed in py3) with str(exception)
